# name: Deploy to Firebase Hosting
# 'on':
#   push:
#     branches:
#       - master
#       - develop
#   pull_request:

# jobs:
#   build_and_deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - run: npm ci && npm run build
#       - name: Set Firebase service account and project ID
#         id: set_env
#         run: |
#           if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
#             echo "::set-output name=serviceAccount::${{ secrets.FIREBASE_SERVICE_ACCOUNT_UT_DNR_UGS_HAZARDS_PROD }}"
#             echo "::set-output name=projectId::ut-dnr-ugs-hazards-prod"
#           elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
#             echo "::set-output name=serviceAccount::${{ secrets.FIREBASE_SERVICE_ACCOUNT_UT_DNR_UGS_HAZARDS_DEV }}"
#             echo "::set-output name=projectId::ut-dnr-ugs-hazards-dev"
#           else
#             echo "::set-output name=serviceAccount::${{ secrets.FIREBASE_SERVICE_ACCOUNT_UT_DNR_UGS_HAZARDS_DEV }}"
#             echo "::set-output name=projectId::ut-dnr-ugs-hazards-dev"
#           fi
#       - name: Prepare Firebase preview channel ID
#         id: prepare_channel_id
#         run: |
#           CHANNEL_ID="${{ github.head_ref }}"
#           CHANNEL_ID="${CHANNEL_ID//\//-}"
#           echo "::set-output name=channelId::${CHANNEL_ID}"
#       - uses: FirebaseExtended/action-hosting-deploy@v0
#         with:
#           repoToken: '${{ secrets.GITHUB_TOKEN }}'
#           firebaseServiceAccount: '${{ steps.set_env.outputs.serviceAccount }}'
#           projectId: '${{ steps.set_env.outputs.projectId }}'
#           channelId: '${{ steps.prepare_channel_id.outputs.channelId }}'
#           expires: 5d